name: On push
run-name: On push
on:
  - push
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          sdk: 10.0.22621.0
          vsversion: 2022
      - uses: Jimver/cuda-toolkit@v0.2.11
        id: cuda-toolkit
        with:
          cuda: '12.3.1'
              sub-packages:
            - nvcc
      - name: Generate project
        run: cmd.exe /c msvc.bat
      - name: Build
        run: |
          cd msvc
          msbuild hey.sln /property:Configuration=RelWithDebInfo
