name: On push
run-name: On push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  - push
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          sdk: 10.0.22621.0
          vsversion: 2022
      - name: Install CUDA
        id: cuda-toolkit
        uses: bullno1/cuda-toolkit@master
        with:
          cuda: '12.2.0'
          method: network
          sub-packages: '["nvcc", "visual_studio_integration", "cudart", "cublas", "cublas_dev", "thrust"]'
      - name: Generate project
        run: cmd.exe /c msvc.bat
      - name: Build
        run: |
          cd msvc
          msbuild hey.sln /property:Configuration=RelWithDebInfo
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: '12.2.0'
          method: network
          sub-packages: '["nvcc", "cudart", "thrust"]'
          non-cuda-sub-packages: '["libcublas", "libcublas-dev"]'
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16.0"
      - name: Install Mold
        uses: rui314/setup-mold@v1
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.18.x'
      - name: Build
        run: ./build
